run:
  tests: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gocognit
    - godot
    - nestif
    - prealloc
    - testpackage
    - wsl

linters-settings:
  lll:
    line-length: 140
  funlen:
    lines: 70
    statements: 50
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - funlen
        - dupl
    - path: "_test.go"
      linters:
        - gocritic
      text: 'hugeParam\: \S+ is heavy \(\d+ bytes\)\; consider passing it by pointer'
